# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04grpc\"%\n\x04Note\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0c\x43onfirmation\x12\r\n\x05value\x18\x01 \x01(\x08\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t2`\n\nChatServer\x12&\n\nChatStream\x12\n.grpc.User\x1a\n.grpc.Note0\x01\x12*\n\x08SendNote\x12\n.grpc.Note\x1a\x12.grpc.Confirmationb\x06proto3')



_NOTE = DESCRIPTOR.message_types_by_name['Note']
_CONFIRMATION = DESCRIPTOR.message_types_by_name['Confirmation']
_USER = DESCRIPTOR.message_types_by_name['User']
Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Note)
  })
_sym_db.RegisterMessage(Note)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Confirmation)
  })
_sym_db.RegisterMessage(Confirmation)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.User)
  })
_sym_db.RegisterMessage(User)

_CHATSERVER = DESCRIPTOR.services_by_name['ChatServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTE._serialized_start=20
  _NOTE._serialized_end=57
  _CONFIRMATION._serialized_start=59
  _CONFIRMATION._serialized_end=88
  _USER._serialized_start=90
  _USER._serialized_end=110
  _CHATSERVER._serialized_start=112
  _CHATSERVER._serialized_end=208
# @@protoc_insertion_point(module_scope)
